167994447 Create database models
andela/rogue-backend pull request #22
Opened 2019-08-20 16:44 UTC by victor-shagor

#### What does this PR do?
         creates database models
#### Description of Task to be completed?
          create database models and migrations
#### How should this be manually tested?
* Clone the repo and `cd` into the project directory
* Run `yarn install` to install the project's dependency
* Setup environment variables
* Run `yarn migrate'

#### What are the relevant pivotal tracker stories?
[#167994447](https://www.pivotaltracker.com/story/show/167994447)

#### Any background context you want to add?

2019-08-20 19:24 UTC, minlinx commented
Nice job, I think the **userId** column should be **owner** and a **foreign** **key**,  I don't think the **dev-start** script is that necessary, may be we should use **prestart** intead of **build** , check if the **build** folder already exists, remove it before **babel** ...

2019-08-21 09:18 UTC, Daymorelah requested changes

2019-08-21 09:18 UTC, Daymorelah commented on src/models/User.js
> +        // associations can be defined here
Remove this comment.

2019-08-21 09:18 UTC, Daymorelah commented on src/models/accommodations.js
> +        Accommodations.hasMany(models.User, {
Remove the comment on line 12

2019-08-21 09:18 UTC, Daymorelah commented on src/models/requests.js
> +        // associations can be defined here
Remove this comment.

2019-08-21 10:10 UTC, Daymorelah requested changes

2019-08-21 10:10 UTC, Daymorelah commented on src/config/config.js
> +module.exports = config;
remove the code on line 10 `operatorsAliases: false`

2019-08-21 10:52 UTC, Daymorelah reviewed
LGTM!

2019-08-21 10:54 UTC, merged