#167727650 Add Search Functionality For Trip Requests
andela/rogue-backend pull request #46
Opened 2019-09-02 23:30 UTC by ChidozieGabriel

#### What does this PR do?
Create route that queries trip requests according to its:
- id
- origin 
- destination
- flightDate
- returnDate
- reason
- owner
- status

#### Description of Task to be completed?
- Create `GET /api/v1/request/search` route

#### How should this be manually tested?
* Clone the repo and `cd` into the project directory
* Run `yarn install` to install the project's dependency
* Run `yarn test` to test the app

#### What are the relevant pivotal tracker stories?
[#167727650](https://www.pivotaltracker.com/story/show/167727650)

2019-09-03 08:51 UTC, 0xciph3r submitted a review, later dismissed

2019-09-03 09:11 UTC, chrismeeky submitted a review, later dismissed
Good job !

2019-09-03 13:38 UTC, okikiola11 submitted a review, later dismissed
This is really looks good.

2019-09-04 04:13 UTC, Daymorelah reviewed
Good job @ChidozieGabriel. However, I need you to re-implement your route handler/Controller to be dynamic such that whatever query params is being sent from the frontend can be used to retrieve data based on the query param. Your current implementation relies on manually checking which query param was passed. This action should dynamic. Reach out to me if you need more clarity on this.

2019-09-04 09:00 UTC, Daymorelah requested changes

2019-09-04 09:00 UTC, Daymorelah commented on src/models/User.js
> +
We dont need this association definition since the association between users n request table has been defined already.

2019-09-04 09:00 UTC, Daymorelah commented on src/routes/requestRoute.js
> +import { Authorization, SearchRequestsMiddleware } from '../middlewares';
I don't think a search middleware is neccesarry for this feature.

2019-09-04 10:24 UTC, merged